name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    name: Nx Cloud - Main Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      # Nx Cloud authentication
      - name: Initialize Nx Cloud
        run: npx nx-cloud start-ci-run

      # Run parallel jobs
      - name: Run lint
        run: npx nx affected --target=lint --parallel=3
      
      - name: Run tests
        run: npx nx affected --target=test --parallel=3
      
      - name: Run build
        run: npx nx affected --target=build --parallel=3

      - name: Stop Nx Cloud agents
        run: npx nx-cloud stop-all-agents
        if: ${{ always() }}